[server]
address = "127.0.0.1"
port = 18502
headless = true
enableXsrfProtection = true
enableCORS = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = "none"

[theme]
primaryColor = "#087F8C"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#172B4D"
font = "sans serif"
